# Generated by Django 3.0.8 on 2021-05-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('zip_code', models.CharField(max_length=400)),
                ('main_image', models.ImageField(blank=True, upload_to='clubs')),
                ('slug', models.SlugField(max_length=400)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courts.City')),
            ],
        ),
    ]
