# Generated by Django 3.0.8 on 2021-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
